---
- name: send the mail
  hosts: <Instance IP/FQDN>
  remote_user: root
  tasks:
    - name: list the inventory file name 
      shell: ls  /root/inv_audit_generator/*.xlsx
      register:  inv_file
    - name: print the file name 
      debug:
        msg: "{{ inv_file.stdout_lines}}"
    - mail:
       host: <SMTP IP>
       port: 25
       to: <email@mail.com>
       from: ansible-report-developer-noreply@mail.com
       subject: "Workflow Report"
       body: |
           Hello Team,
           
           PFA.
           
           Thanks and Regards,
           Ansible Tower

       attach: "{{ inv_file.stdout_lines }}"
