---
- name: send the mail
  hosts: 10.226.73.29
  remote_user: root
  tasks:
    - name: list the wf file name 
      shell: ls  /root/wf_audit_generator/*.xlsx
      register:  wf_file
    - name: print the file name 
      debug:
        msg: "{{ wf_file.stdout_lines}}"
    - mail:
       host: 10.226.15.193
       port: 25
       to: ansible.developer@hdfcbank.com,sarat.palukurty@hdfcbank.com,irfan.sheik@hdfcbank.com
       subject: "WorkFlow Report"
       body: |
           Hello Team,
           
           PFA.
           
           Thanks and Regards,
           Ansible Tower

       attach: "{{ wf_file.stdout_lines }}"
