---
- name: Playbook to check the Server Accesibility
  hosts: "{{ Deployment_host }}" 
  gather_facts: false      
  vars_files:
    - CyberArk_vault.yml
  tasks:
   - name: inculde the CyberArk task 
     include_tasks: CyberArk2.yml

   - block:
        - name: Ping the servers
          ping:
          delegate_to: localhost
          register: hostlist
          
        - name: Print The MSG.
          debug:
            msg: "Systems are Reachable"
     rescue:
        - name: Verify the unreachable host
          debug:
            msg: "Unreachable Host: {{item.item}}"
          when: true == item.failed
          loop: "{{ hostlist.results}}"
          loop_control:
            label: "{{ ansible_loop_var }}"
            
        - name: Verify the Reachable host
          debug:
            msg: "Reachable Host: {{item.item}}"
          when: true != item.failed
          loop: "{{ hostlist.results}}"
          loop_control:
            label: "{{ ansible_loop_var }}"
            
        - name:  Terminating the workflow
          debug:
            msg: "Workflow Terminated"
          failed_when: true == item.failed
          loop: "{{ hostlist.results}}"
          loop_control:
            label: "{{ ansible_loop_var }}"
